[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["no-std"]
description = "serde-json for no_std programs"
documentation = "https://docs.rs/serde-json-core"
edition = "2018"
keywords = ["serde", "json"]
license = "MIT OR Apache-2.0"
name = "serde-json-core"
readme = "README.md"
repository = "https://japaric.github.io/serde-json-core/serde_json_core"
version = "0.0.1"

[dependencies]
heapless = "0.5.1"

[dependencies.serde]
default-features = false
version = "1.0.102"

[dev-dependencies]
serde_derive = "1.0.102"

[features]
std = ["serde/std"]
